/*
    This file was generated automatically by Alchitry Labs 2.0.41-BETA.
    Do not edit this file directly. Instead edit the original Lucid source.
    This is a temporary file and any changes made to it will be destroyed.
*/

module alchitry_top (
        input wire clk,
        input wire rst_n,
        output reg [7:0] led,
        input wire usb_rx,
        output reg usb_tx,
        input wire ft_clk,
        input wire ft_rxf,
        input wire ft_txe,
        inout wire [15:0] ft_data,
        inout wire [1:0] ft_be,
        output reg ft_rd,
        output reg ft_wr,
        output reg ft_oe,
        output reg ft_wakeup,
        output reg ft_reset
    );
    logic rst;
    localparam _MP_STAGES_1420874663 = 3'h4;
    logic M_reset_cond_in;
    logic M_reset_cond_out;
    
    reset_conditioner #(
        .STAGES(_MP_STAGES_1420874663)
    ) reset_cond (
        .clk(clk),
        .in(M_reset_cond_in),
        .out(M_reset_cond_out)
    );
    
    
    localparam _MP_BUS_WIDTH_528252186 = 5'h10;
    localparam _MP_TX_BUFFER_528252186 = 9'h100;
    localparam _MP_RX_BUFFER_528252186 = 9'h100;
    localparam _MP_PRIORITY_528252186 = {{8'h52, 8'h58}};
    localparam _MP_PREEMPT_528252186 = 1'h0;
    logic M_ft_ft_rxf;
    logic M_ft_ft_txe;
    logic M_ft_ft_rd;
    logic M_ft_ft_wr;
    logic M_ft_ft_oe;
    logic [15:0] M_ft_ui_din;
    logic [1:0] M_ft_ui_din_be;
    logic M_ft_ui_din_valid;
    logic M_ft_ui_din_full;
    logic [15:0] M_ft_ui_dout;
    logic [1:0] M_ft_ui_dout_be;
    logic M_ft_ui_dout_empty;
    logic M_ft_ui_dout_get;
    
    ft #(
        .BUS_WIDTH(_MP_BUS_WIDTH_528252186),
        .TX_BUFFER(_MP_TX_BUFFER_528252186),
        .RX_BUFFER(_MP_RX_BUFFER_528252186),
        .PRIORITY(_MP_PRIORITY_528252186),
        .PREEMPT(_MP_PREEMPT_528252186)
    ) ft (
        .ft_clk(ft_clk),
        .ft_data(ft_data),
        .ft_be(ft_be),
        .clk(clk),
        .rst(rst),
        .ft_rxf(M_ft_ft_rxf),
        .ft_txe(M_ft_ft_txe),
        .ft_rd(M_ft_ft_rd),
        .ft_wr(M_ft_ft_wr),
        .ft_oe(M_ft_ft_oe),
        .ui_din(M_ft_ui_din),
        .ui_din_be(M_ft_ui_din_be),
        .ui_din_valid(M_ft_ui_din_valid),
        .ui_din_full(M_ft_ui_din_full),
        .ui_dout(M_ft_ui_dout),
        .ui_dout_be(M_ft_ui_dout_be),
        .ui_dout_empty(M_ft_ui_dout_empty),
        .ui_dout_get(M_ft_ui_dout_get)
    );
    
    
    always @* begin
        M_reset_cond_in = ~rst_n;
        rst = M_reset_cond_out;
        led = {ft_txe, ft_rxf, M_ft_ui_dout_empty, M_ft_ui_din_full};
        usb_tx = usb_rx;
        M_ft_ft_rxf = ft_rxf;
        M_ft_ft_txe = ft_txe;
        ft_rd = M_ft_ft_rd;
        ft_wr = M_ft_ft_wr;
        ft_oe = M_ft_ft_oe;
        ft_wakeup = 1'h1;
        ft_reset = !rst;
        M_ft_ui_dout_get = !M_ft_ui_din_full;
        M_ft_ui_din_valid = !M_ft_ui_dout_empty;
        M_ft_ui_din = M_ft_ui_dout;
        M_ft_ui_din_be = M_ft_ui_dout_be;
    end
    
    
endmodule