
-------------------------------------------------
-- rtl/version_pkg.vhd
--------------------------------------------------
--
-- Copyright 2025 Shure Incorporated
-- CONFIDENTIAL AND PROPRIETARY TO SHURE
--
--------------------------------------------------
--
-- This pkg file is auto-generated by fpga_build.py and 
-- contains the version and date/time information.
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package version_pkg is

    -- Note in order to get a build version of 0, you are able to manually put a -1 for BUILD and the fpga_build.read_pkg_version_and_update()
    -- will have it roll around to 0 without incrementing the minor number for a roll around.
    constant C_VERSION_MAJOR   : std_logic_vector(07 downto 0) := std_logic_vector(to_unsigned(   7,8));
    constant C_VERSION_MINOR   : std_logic_vector(07 downto 0) := std_logic_vector(to_unsigned(   9,8));
    constant C_VERSION_PATCH   : std_logic_vector(07 downto 0) := std_logic_vector(to_unsigned(   0,8));
    constant C_VERSION_BUILD   : std_logic_vector(07 downto 0) := std_logic_vector(to_unsigned(   0,8));
    constant C_VERSION_YEAR    : std_logic_vector(15 downto 0) := X"2025";
    constant C_VERSION_MONTH   : std_logic_vector(07 downto 0) := X"10";
    constant C_VERSION_DAY     : std_logic_vector(07 downto 0) := X"20";
    constant C_VERSION_HOUR    : std_logic_vector(07 downto 0) := X"15";
    constant C_VERSION_MINUTE  : std_logic_vector(07 downto 0) := X"04";
    constant C_VERSION_SECOND  : std_logic_vector(07 downto 0) := X"33";

end version_pkg;
--------------------------------------------------------------------------------
