#!/usr/bin/env bash
#################################################################################
##
## deploy_artifactory
##
## Copies files into an output directory to stage for deploying to artifactory
##
## then uses deploy_artifactory.py to make them go brrr to artifactory.
##
## run from ./par
##
#################################################################################
set -e

mkdir -p artifactory/staging/dist
mkdir -p artifactory/staging/meta
mkdir -p artifactory/staging/meta/par
mkdir -p artifactory/staging/meta/log
mkdir -p artifactory/staging/meta/gen

# fail if these files don't exist

artifact_component="ATLAS/protonpack"

BASE="alchitry_top"

# generally ignore failures if files don't exist, we don't want to prevent artifactory deploys
# that might have useful debug info in them, because developer time is valuable
set +e

# why is this dist vs meta?
# answer: https://confluence.shure.com/display/DEVOPS/Common+Tool+Chain+Integration
# https://confluence.shure.com/display/DEVOPS/Save+Component+Artifacts

# first select dist files
   
cp par/output/*_working.bin artifactory/staging/dist
cp par/output/*_working.mcs artifactory/staging/dist
cp par/output/*_working_FAILED.bin artifactory/staging/dist # in case it fails timing we don't want it to be loaded onto a board without manual intervention, so append _FAILED to break the pipeline
cp par/output/*_working_FAILED.mcs artifactory/staging/dist

# then select meta files
# sort-lines alphabetize

# place and route outputs other than distributable binaries
cp par/output/*.ltx artifactory/staging/meta/par
cp par/output/*.prm artifactory/staging/meta/par
cp par/output/post_opt.dcp artifactory/staging/meta/par
cp par/output/post_opt_control_sets.rpt artifactory/staging/meta/par
cp par/output/post_opt_control_sets.rpt artifactory/staging/meta/par
cp par/output/post_opt_util.rpt artifactory/staging/meta/par
cp par/output/post_opt_util.rpt artifactory/staging/meta/par
cp par/output/post_route.dcp artifactory/staging/meta/par
cp par/output/post_route_control_sets.rpt artifactory/staging/meta/par
cp par/output/post_route_timing_summary.rpt artifactory/staging/meta/par
cp par/output/post_route_util.rpt artifactory/staging/meta/par
cp par/output/post_synth.dcp artifactory/staging/meta/par
cp par/output/post_synth_control_sets.rpt artifactory/staging/meta/par
cp par/output/post_synth_util.rpt artifactory/staging/meta/par
cp par/output/report_cdc.rpt artifactory/staging/meta/par
cp par/output/report_cdc_waived.rpt artifactory/staging/meta/par
cp par/output/report_cdc_waivers.rpt artifactory/staging/meta/par


# logs of output console, python and os environment, 
cp apt-list-installed.txt artifactory/staging/meta/log
cp revision_info.rpt artifactory/staging/meta/log
cp par/vivado.log artifactory/staging/meta/log
cp requirements-export.txt artifactory/staging/meta/log

# generated intermediate files
cp rtl/version_pkg.sv artifactory/staging/meta/gen


# add --developer if you need to deploy a local build as your user
#python -m scripts.deploy_artifactory $artifact_component  --developer
python -m scripts.deploy_artifactory $artifact_component $1
