#!/usr/bin/env bash
# scripts/jenkins_config
# script to be copied into jenkins config or called from jenkins config

# show commands
set +x
# stop on all errors (e.g. to error if branch is wrong)
set -e
# set -u doesn't work for vivado
# /data/Xilinx/2025.1/Vitis/.settings64-Vitis.sh: line 13: PYTHONPATH: unbound variable

## CHECKOUT DESIGN

# blow away our working location to always build fresh
rm -rf protonpack

git clone --filter=tree:0 --no-checkout --quiet ssh://git@bitbucket.shure.com:7999/dpsm_fpga/protonpack.git
cd protonpack
git checkout --no-progress $branch


## launch the build
source ./build_fpga $branch
