#!/usr/bin/env bash

set -e

# https://stackoverflow.com/questions/59895/how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itsel
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

## set vivado version for hw mgr
#source $SCRIPT_DIR/setup_vivado

# todo: remove dependency on alchitry by spinning a custom board.
alchitry load --flash --board "Alchitry Pt V2" --bin par/output/alchitry_top_working.bin 


