#!/usr/bin/env python
import bash

import os
def revision_info(rootdir):
    # print out revision info for each subdirectory that seems to be svn or git controlled
    # always try to print info in current directory in case it is a subdirectory of a git project
    # this will create a log of all versions used to create a build in case there is every a question
    print("Revision info report:")
    for subdir, dirs, files in os.walk(rootdir):
        if ".svn" in subdir:
            svn_dir,tail = os.path.split(subdir)
            #print(svn_dir)
            svn_report(svn_dir)
    for subdir, dirs, files in os.walk(rootdir):
        if ".git" in subdir: 
            #print("aha")
            git_dir,tail = os.path.split(subdir)
            print(git_dir)
            git_report(git_dir)
        elif subdir == ".":
            # always run git commands in starting directory in case it is a child without .git
            print(".")
            try: 
                git_report(".")
            except ValueError as e:
                print("WARNING: bash command failed. Is this directory not version controlled by git?")

def svn_report(dir):
    bash.bash(f"svn info {dir}")
    bash.bash(f"svn status -v {dir}")

def git_report(dir):    
    #https://stackoverflow.com/questions/924574/git-alternatives-to-svn-info-that-can-be-included-in-a-build-for-traceability
    bash.bash(f"cd {dir} && git remote -v")
    bash.bash(f"cd {dir} && git rev-parse HEAD")
    bash.bash(f"cd {dir} && git diff --name-status HEAD")

if __name__ == "__main__":
   revision_info('.')
