#!/usr/bin/env bash

# generates the file lists and runs vivado

set -e
(
scripts/generate_telem_pkg
source scripts/activate_vivado
scripts/compile_file_generation
cd par
time vivado -mode batch -source build.tcl -notrace
cd ..
)