#!/usr/bin/env bash
# setup_python is designed to leave you with an environment that matches requirements.txt or error out.

# The canonical version of this file is here: 
# 
# https://bitbucket.shure.com/projects/ATLASFPGA/repos/atlas-base/browse/scripts
# 
# If improvements are made they should be put in the canonical version.
# The Python champion listed here should be consulted to coordinate any changes:
# 
# https://bitbucket.shure.com/projects/ATLASFPGA/repos/atlas-base/browse/doc/atlas_design_process/md/design_process.md


# For Jenkins specifically:
# 
# uses setup_jenkins: which always creates the same environment name so conflicts won't be an issue.
# the location will always be in /home/secbuild/.virtualenvs/ ...
# jenkins can only run 1 pipeline on a system at a time, only 1 executor so this isn't
# an issue either
# name used in scripts/setup_jenkins out of sync issue is a quick fix, just need to fix
# the typo in one location
#  
# 
# For typical users, the setup_python script is handling these concerns also.
# 
# Specifically for users of dpsm_rx_hw_test only:
# setup_python creates a unique environment name based off of the path to the workspace.
# Bryan requested this as he has multiple environments and branches checked out at once,
# so he did not want all of them to be linked to the same virtualenv
# We cannot have the virtualenv be placed inside the workspace like it was with conda
# inside .cenv; we tried and it does not allow for this function.
# race conditions: unless the user is also running setup_python as part of the job, I
# don't know how this could even occur. if we are talking about slurm, then we may need
# to just create a setup_slurm script (cc Andrew Sinnett )
# out of sync issue: the name of the environment is actually a variable in setup_python
# and called through the whole script, nothing to worry about
 

# check if this was called by source to prevent incorrect usage
(return 0 2>/dev/null) && sourced=1 || sourced=0

if [ $sourced -eq 1 ]; then
    echo "do not source this command, please run it directly."
    return
fi


# can't set -u because virtualenv wrapper uses extensive undefined variables
# can't set -o pipefail because of virtualenv wrapper as well?
set -e
   
# https://unix.stackexchange.com/questions/162165/check-that-a-bash-script-has-exactly-two-arguments-which-are-directories
REPONAME=$(pwd | sed -e 's|^/||' -e 's|/|__|g') #make a unique virtualenv based off the current path

#echo $REPONAME

# try to find it no matter how it was installed
echo "finding virtualenvwrapper.sh and running it"
source $(locate virtualenvwrapper.sh | tail -n 1)

# don't build this fresh. Reuse the old environment if it already exists.
if [ ! -d ~/.virtualenvs/${REPONAME} ]; then
    # to avoid bugs with mkvirtualenv, workon and -euo pipefail, temporarily turn it off.
    set +e
    mkvirtualenv -p python3.11 --pip 25.1.1 --setuptools 80.0.1 ${REPONAME} || exit 2
    workon ${REPONAME} || exit 3
    set -e

    pip install -r requirements.txt
    # to allow us to know what was in an environment that worked
    # so when it inevitably fails we can do a diff
    # todo: this should also go to the log file and/or back to bitbucket
    pip freeze > requirements-export.txt

    # link to src so hard coded stuff doesn't break (e.g. compile_iq_telemetr.txt calling out shurc_assembler
    ln -fs ~/.virtualenvs/${REPONAME}/src ./src
else
    echo "Virtualenv already exists at ~/.virtualenvs/${REPONAME}."
    echo "If requirements.txt has changed, you must delete it before re-running setup_jenkins:"
    echo "source scripts/cleanup_python"
    echo "Otherwise activate your existing environment with the following command:"
    echo "source scripts/activate_python"
    
    # setup_python is designed to leave you with an environment that matches requirements.txt or error out.
    # setup_python must be run exactly once on new machines or if requirements.txt has changed.
    # If the environment already exists it errors out to prevent a potential mismatch between a stale environment
    # and an updated requirements.txt.
    # re-running it should be considered an error and stop subsequent steps. This will prevent
    # running in a stale environment and wasting time trying to determine why it doesn't work.
    exit 1
fi

# also for debug when things go sideways
apt list --installed > apt-list-installed.txt

echo "======================================================="
echo "Existing virtualenvs:"
lsvirtualenv
echo "To remove your virtualenvironment use the following command:"
echo "source scripts/cleanup_python"
echo "======================================================="
echo "Use the following commands to activate your environment:"
echo "source scripts/activate_python"
