#!/usr/bin/env bash
# build via jenkins. Only Digital image type. Open console in browser
# if you get:
# HTTP ERROR 401 Unauthorized
# generate a new token on jenkins:
# https://fpga.jenkins-ecs.shure.com/user/lastf/security/
# and put it in ~/.jenkins_token
# like so:
# API_TOKEN=112a99c0e293e2f0154812b11b5e3c0345
# API_USER=lastf

set -e

# https://unix.stackexchange.com/questions/162165/check-that-a-bash-script-has-exactly-two-arguments-which-are-directories
if [ $# -ne 1 ]; then
  echo 1>&2 "Usage: $0 branch_name"
  exit 3
fi

BRANCH=$1
# pull in API_TOKEN and API_USER, to avoid storing them in github
source ~/.jenkins_token

# kick off builds

# needs -k because of sketchy shure certificate:
# curl: (60) SSL certificate problem: self-signed certificate in certificate chain
# More details here: https://curl.se/docs/sslcerts.html


# https://stackoverflow.com/questions/20359810/how-to-trigger-jenkins-builds-remotely-and-to-pass-parameters
curl -k -X POST "https://fpga.jenkins-ecs.shure.com/job/DEVELOPMENT/job/TELEMETRY/job/protonpack/buildWithParameters?branch=$BRANCH" --user $API_USER:$API_TOKEN

# delay to run sim last so it doesn't block any builds
sleep 1
# and simulate
#curl -k -X POST "https://fpga.jenkins-ecs.shure.com/job/SIMULATION/job/DPSM/job/DPSM_RX_Digital_Sim/buildWithParameters?branch=$BRANCH" --user $API_USER:$API_TOKEN


# monitor results
# at end, to not accidentally block jobs if running via ssh
xdg-open https://fpga.jenkins-ecs.shure.com/job/DEVELOPMENT/job/TELEMETRY/job/protonpack/
#xdg-open https://fpga.jenkins-ecs.shure.com/job/SIMULATION/job/DPSM/job/DPSM_RX_Digital_Sim/
