#!/usr/bin/env bash
#################################################################################
## call python from bash
#################################################################################

python -m scripts.fpgabuild.compile_file_generation par compile.txt
