#!/usr/bin/env python
#################################################################################
##
## creates an initial_values string to pass to csv scripts
##
## Nicholas Dietz
##
#################################################################################
from fpgabuild import fpga_build

rtl_version_file="rtl/version_pkg.v"
## instantiate the helper build scripts
## This reads the current revision from the rtl version package file
build = fpga_build.fpga_build(rtl_version_file=rtl_version_file)

# a commit message containing the url and version of the artifactory commit. For checking in auto generated code created as part of the build process.
print(build.get_version())
