#!/usr/bin/env python
#################################################################################
##
## deploy_artifactory
##
## Alex Stezskal, Nicholas Dietz
##
##
## To set up for a new project, the artifact_component variable must be set correctly
##
#################################################################################
from fpgabuild import fpga_build


artifact_component="ATLAS/protonpack"

rtl_version_file="rtl/version_pkg.v"
## instantiate the helper build scripts
## This reads the current revision from the rtl version package file
build = fpga_build.fpga_build(rtl_version_file=rtl_version_file)

## When we commit a new version_pkg file back to source control, the log msg will contain the artifactory URL for reference
# a commit message containing the url and version of the artifactory commit. For checking in auto generated code created as part of the build process.
artifactory_url_all_shure="https://artifactory.shure.com/All_Shure_Components/"+artifact_component+"/"+build.get_version()+"/"
msg=artifactory_url_all_shure+" Artifactory auto commit from build."

print(msg)