#!/usr/bin/env python
#################################################################################
##
## update version
## Read the current revision from the rtl version package file, update the version, then recreate the version package file
#################################################################################
from fpgabuild import fpga_build

rtl_version_file="rtl/version_pkg.v"
## instantiate the helper build scripts
## This reads the current revision from the rtl version package file
build = fpga_build.fpga_build(rtl_version_file=rtl_version_file)
build.update_version()  
build.write_pkg_version()
