#!/usr/bin/env bash
set -e

# https://riptutorial.com/bash/example/30284/change-to-the-directory-of-the-script
cd "$(dirname "$(readlink -f "$0")")"

gcc async-loopback-to-disk.c -o async-loopback-to-disk -lftd3xx -L/usr/local/lib -Ilinux-x86_64/
#gcc speed_test.c -o speed_test -lftd3xx -L/usr/local/lib -Ilinux-x86_64/
#gcc async-loopback-clean.c -o async-loopback-clean -lftd3xx -L/usr/local/lib -Ilinux-x86_64/
#gcc write_test.c -o write_test -lftd3xx -L/usr/local/lib -Ilinux-x86_64/
time ./async-loopback-to-disk
#time ./speed_test
#time ./async-loopback-clean
#./write_test
python check_bin.py loopback_async.bin
ls -alrth *.bin
